language: ruby
rvm:
  - "2.2.1"
  - "2.2.2"
env:
  - "RAILS_VERSION=4.1.9"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0.beta1"

matrix:
  exclude:
    - rvm: 2.2.1
    - env: "RAILS_VERSION=5.0.0.beta1"

addons:
  code_climate:
    repo_token: 970a221275a9af67dcd65c19f074b8f5e94581c97ab883ad6a974dd4b425b3bc
