language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0

env:
  - "RAILS_VERSION=5.2.4.4"
  - "RAILS_VERSION=6.0.3.4"

addons:
  code_climate:
    repo_token: 9b174f785a3f1ad8986730da28c2756320f0413067e7e06bad278280f47743fd

after_success:
  - bundle exec codeclimate-test-reporter
