language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

env:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.1"
  - "RAILS_VERSION=5.1.0.beta1"

matrix:
  exclude:
    - rvm: 2.2.6
      env: "RAILS_VERSION=5.0.1"

addons:
  code_climate:
    repo_token: 970a221275a9af67dcd65c19f074b8f5e94581c97ab883ad6a974dd4b425b3bc
